// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

declare const process: {
  env: Record<string, string | undefined>;
};

// Prisma CLI config (migrate, generate, validate). The running app does not read this file.
export default defineConfig({
  // Where the data models live
  schema: "prisma/schema.prisma",
  // Where generated migration files are stored
  migrations: {
    path: "prisma/migrations",
    // Command run by `npx prisma db seed`
    seed: "tsx prisma/seed.ts",
  },
  // Direct (non-pooled) Neon connection, required for running migrations
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
